config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'main#index'

  devise_for :users
    namespace :admin do
      root to: 'main#index'
      resources :users
      resources :vaccines_items
      resources :bookings
      resources :patients
      resources :business_units
      resources :business_unit_slots
      resources :districts
      get '/countries/fetch_cities'
      resources :countries
      get '/cities/fetch_districts'
      resources :cities
      resources :orders
      resources :sms
    end
  end

  get 'slots/fetch_cities'
  get 'slots/fetch_districts'
  get 'slots/fetch_business_units'
  resources :slots, only: [:index]

  match 'bookings/:vaccine', to: 'main#current_step', via: :get, as: :current_step
  match 'next_step', to: 'main#next_step', via: :post
  match 'prev_step', to: 'main#prev_step', via: :post

  get 'order_cancellations/find_order'
  post 'order_cancellations/send_verification'
  post 'order_cancellations/verify_code'
  resources :order_cancellations
end

app/controllers/admin/main_controller.rb
module Admin
  # ...
  class MainController < ApplicationController
    def index; end
  end
end

app/controllers/main_controller.rb
# ...
class MainController < ApplicationController
  before_action :fetch_booking, only: %i[current_step next_step prev_step]
  before_action :clear_booking

  def index
    @vaccine_items = VaccinesItem.active

    @bu_unit_slot = BusinessUnitSlot.active

    @slots_quantity = Slots::SqlService.new(@bu_unit_slot).slots.length
  end

  def current_step
    result = Web::CurrentStepService.call(booking: @booking, params: params, collect_analytics: collect_analytics)

    if result.success? && result.record.present?
      assign_step_variables({ vaccine: result.current_vaccine, record: result.record })

      cookies.signed[:booking_uuid] = result.booking.guid

      render "main/steps/step#{result.render_step}"
    else
      cookies.delete(:booking_uuid)

      redirect_to root_url, notice: result.message
    end
  end

  def next_step
    return redirect_to root_url, notice: I18n.t('web.main.session_expired') unless @booking

    result = Web::NextStepService.call(booking: @booking, params: params)

    if result.success?
      if result.last_step?
        cookies.delete(:booking_uuid)

        return redirect_to root_url, notice: I18n.t('web.main.booking_success')
      end

      redirect_to current_step_path(result.booking.vaccine&.name)
    else
      assign_step_variables({ vaccine: result.booking.vaccine, record: result.record })

      render "main/steps/step#{result.current_step}"
    end
  end

  def prev_step
    return redirect_to root_url, notice: I18n.t('web.main.session_expired') unless @booking

    result = Web::PrevStepService.call(booking: @booking, params: params)

    if result.success?
      return delete_cookies if result.first_step?

      redirect_to current_step_path(result.booking.vaccine&.name&.downcase)
    else
      assign_step_variables({ vaccine: result.booking.vaccine, record: result.record })

      render "main/steps/step#{result.current_step}"
    end
  end

  private

  def assign_step_variables(attrs)
    @current_vaccine = attrs[:vaccine]
    @record = attrs[:record]
  end

  def fetch_booking
    booking_uuid = cookies.signed[:booking_uuid]

    if booking_uuid.present?
      @booking = Booking.find_by(guid: booking_uuid)
    end
  end

  def collect_analytics
    browser = Browser.new(request.env['HTTP_USER_AGENT'])
    {
    user_ip: request.remote_ip,
    browser: browser.name,
    platform: browser.platform.name
    }
  end

  def clear_booking
    if @booking&.finished?
      delete_cookies
    end
  end

  def delete_cookies
    cookies.delete(:booking_uuid)
    redirect_to root_path
  end
end

app/views/main/steps/step0.html.erb
<h1>Registration</h1>

<div class="row">
  <div class="col">
    <div class="card h-100">
      <div class="card-body">
	<h5 class="card-title"><strong><%= @current_vaccine.name %></strong></h5>
	<br />
	<%= simple_form_for @record, method: :post, url: next_step_path do |f| %>
	  <%= f.input :first_name %>
	  <%= f.input :last_name %>
	  <%= f.input :birth_date, as: :date, start_year: 1900, end_year: Date.current.year %>
	  <%= f.input :pin %>
	  <%= f.input :non_resident, as: :boolean %>
	  <%= f.input :mobile_phone %>
	  <%= f.input :email %>
<br>
			<div class="btn-toolbar">
				<div class="btn-group me-2">
					<%= link_to '< Prev', prev_step_path, type: "button", method: :post, class: 'btn btn-outline-dark'  %>
				</div>
				<div class="btn-group me-2">
					<%= f.submit I18n.t('web.main.step0_submit'), class: 'btn btn-success' %>
				</div>
			</div>
		
	<% end %>
      </div>

      <div class="card-footer">
				<small class="text-muted">
					<nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
						<ol class="breadcrumb">
							<li class="breadcrumb-item"><%= link_to 'Home', root_url %></li>
							<li class="breadcrumb-item active" aria-current="page">Registration (<%= @current_vaccine.name %>)</li>
						</ol>
					</nav>
				</small>
      </div>
    </div>
  </div>
</div> 

app/views/main/steps/step1.html.erb
<h1>Booking</h1>

<% if @record.errors[:base].present? %>
  <% @record.errors.each do |error| %>
    <div class="alert alert-danger" role="alert">
      <%= error.full_message %>
    </div>
  <% end %>
<% end %>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Choose Booking Time</h5>

    <%= form_for :slots, html: { class: 'form' } do |f| %>
    <% @bu_unit = BusinessUnitPresenter.new(@record.business_unit_slot&.business_unit) %>

    <div class="row" data-controller="slots"
                      data-slots-country-id-value="<%= @bu_unit.country_id %>"
                      data-slots-city-id-value="<%= @bu_unit.city_id %>"
                      data-slots-district-id-value="<%= @bu_unit.district_id %>"
                      data-slots-bu-unit-id-value="<%= @bu_unit.id %>"
                      data-slots-order-date-value="<%= @record.order_date.to_i %>"
                      >

      <div class="col">
        <%= f.collection_select :country_id, Country.active, :id, :name,
          { include_blank: 'Select Country', selected: @bu_unit.country_id },
          class: 'form-select',
          data: {
            action: "change->slots#fetchCities",
            slots_target: "country"
          }
        %>
      </div>

      <div class="col">
        <%= f.collection_select :city_id, [], :id, :name,
          { include_blank: 'Select City' },
          class: 'form-select',
          data: {
            action: "change->slots#fetchDistricts",
            slots_target: "city"
          }
        %>
      </div>

      <div class="col">
        <%= f.collection_select :district_id, [], :id, :name,
          { include_blank: 'Select District' },
          class: 'form-select',
          data: {
            action: "change->slots#fetchBusinessUnits",
            slots_target: "district"
          }
        %>
      </div>

      <div class="col">
        <%= f.collection_select :business_unit_id, [], :id, :name,
          { include_blank: 'Select Business Unit' },
          class: 'form-select',
          data: {
            action: "change->slots#fetchSlots",
            slots_target: "bu_unit"
          }
        %>
      </div>

          <div class="col">
            <%= f.button 'Reload', type: 'button',
              class: 'btn btn-dark',
              data: {
                action: "click->slots#fetchSlots",
                slots_target: "refresh"
              },disabled: true
            %>
          </div>

          <div class="row" data-slots-target="slots"></div>
        </div>
      <% end %>

    <br />
    <div class="card-body">
      <div class="btn-toolbar">
    
        <div class="btn-group me-2">
          <%= button_to '< Prev', prev_step_path, method: :post, class: 'btn btn-outline-dark'  %>
        </div>
    
        <div class="btn-group me-2">
          <%= simple_form_for @record, method: :post, url: next_step_path do |f| %>
            <%= f.input :order_date, as: :hidden %>
            <%= f.input :business_unit_slot_id, as: :hidden %>
            <%= f.submit I18n.t('web.main.step1_submit'), class: 'step1_submit btn btn-success invisible' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="card-footer">
    <small class="text-muted">
      <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to 'Home', root_url %></li>
          <li class="breadcrumb-item"><%= link_to 'Registration', '#' %></li>
          <li class="breadcrumb-item active" aria-current="page">Booking Slot (<%= @current_vaccine.name %>)</li>
        </ol>
      </nav>
    </small>
  </div>
</div>

app/views/main/steps/step2.html.erb
<br/>

<% if @record.booking.errors[:base].present? %>
  <% @record.booking.errors.each do |error| %>
    <div class="alert alert-danger" role="alert">
      <%= error.full_message %>
    </div>
  <% end %>
<% end %>

<div class="card">
  <div class="card-header">
    <h2>Confirmation - <%= @current_vaccine.name %></h2>
  </div>

  <div class="card-body">
    <h3 class="card-text">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-triangle" viewBox="0 0 16 16">
    <path d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.146.146 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.163.163 0 0 1-.054.06.116.116 0 0 1-.066.017H1.146a.115.115 0 0 1-.066-.017.163.163 0 0 1-.054-.06.176.176 0 0 1 .002-.183L7.884 2.073a.147.147 0 0 1 .054-.057zm1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566z"/>
    <path d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995z"/>
    </svg>
    Please, carefully read booking and personal information and then confirm!
    </h3>
  </div>

  <div class="card-body">
    <h5 class="card-title">Personal info</h5>
    <div class="row">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= I18n.t('web.main.step2.full_name') %>: <strong><%= @record.patient_full_name %></strong>
        </li>
        <li class="list-group-item">
          <%= I18n.t('web.main.step2.birth_date') %>: <strong><%= @record.patient_birth_date %></strong>
        </li>
        <li class="list-group-item">
          <%= I18n.t('web.main.step2.pin') %>: <strong><%= @record.patient_pin %></strong>
        </li>
        <li class="list-group-item">
          <%= I18n.t('web.main.step2.mobile_phone') %>: <strong><%= @record.patient_mobile_phone %></strong>
        </li>

        <li class="list-group-item">
          <%= I18n.t('web.main.step2.email') %>: <strong><%= @record.patient_email %></strong>
        </li>
      </ul>
    </div>
  </div>

  <div class="card-body">
    <h5 class="card-title">Booking</h5>
    <div class="row">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= I18n.t('web.main.step2.order_address') %>: <strong><%= @record.order_business_unit_address %></strong>
        </li>
        <li class="list-group-item">
          <%= I18n.t('web.main.step2.order_date') %>: <strong><%= @record.order_date %></strong>
        </li>
      </ul>
    </div>
  </div>

  <div class="card-body">
    <div class="btn-toolbar">
  
      <div class="btn-group me-2">
        <%= button_to '< Prev', prev_step_path, method: :post, class: 'btn btn-outline-dark' %>
      </div>
  
      <div class="btn-group me-2">
        <%= simple_form_for @record.booking, method: :post, url: next_step_path do |f| %>
          <%= f.submit I18n.t('web.main.step2_submit'), class: 'step1_submit btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer">
    <small class="text-muted">
      <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to 'Home', root_url %></li>
          <li class="breadcrumb-item"><%= link_to 'Registration', '#' %></li>
          <li class="breadcrumb-item"><%= link_to 'Booking Slot', '#' %></li>
          <li class="breadcrumb-item active" aria-current="page">Confirmation (<%= @current_vaccine.name %>)</li>
        </ol>
      </nav>
    </small>
  </div>
</div>