config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'main#index'

  devise_for :users
    namespace :admin do
      root to: 'main#index'
      resources :users
      resources :vaccines_items
      resources :bookings
      resources :patients
      resources :business_units
      resources :business_unit_slots
      resources :districts
      get '/countries/fetch_cities'
      resources :countries
      get '/cities/fetch_districts'
      resources :cities
      resources :orders
      resources :sms
    end
  end

  get 'slots/fetch_cities'
  get 'slots/fetch_districts'
  get 'slots/fetch_business_units'
  resources :slots, only: [:index]

  match 'bookings/:vaccine', to: 'main#current_step', via: :get, as: :current_step
  match 'next_step', to: 'main#next_step', via: :post
  match 'prev_step', to: 'main#prev_step', via: :post

  get 'order_cancellations/find_order'
  post 'order_cancellations/send_verification'
  post 'order_cancellations/verify_code'
  resources :order_cancellations
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :cities
  scope :active, -> { where(active: true) }
end

app/controllers/admin/countries_controller.rb
module Admin
  # ...
  class CountriesController < ApplicationController
    before_action :init_service
    def index
      @pagy, @countries = pagy(@countries_service.list)
    end

    def new
      result = @countries_service.new
      @country = result.country
    end

    def edit
      result = @countries_service.edit(params[:id])

      @country = result.country
    end

    def create
      result = @countries_service.create(country_params)
      @country = result.country

      if result.success?
        redirect_to admin_countries_path, notice: I18n.t('admin.countries.notices.created')
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      result = @countries_service.update(params[:id], country_params)
      @country = result.country

      if result.success?
        redirect_to admin_countries_path, notice: I18n.t('admin.countries.notices.updated')
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      result = @countries_service.delete(params[:id])
      if result.success?
        redirect_to admin_countries_path, notice: I18n.t('admin.countries.notices.destroyed')
      end
    end

    def fetch_cities
      @cities = City.active.by_country(params[:country_id])

      render partial: 'cities', object: @cities, layout: false
    end

    private

    def init_service
      @countries_service = Countries::CountriesService.new
    end

    def country_params
      params.require(:country).permit(:name, :code, :active)
    end
  end
end

app/views/admin/countries/_cities.html.erb
<%=  options_for_select(@cities.map { |c| [c.name, c.id] })%>

app/views/admin/countries/_form.html.erb
<%= simple_form_for [:admin, country] do |f| %>
<%= f.input :name %>
<%= f.input :code %>
<%= f.input :active %>
<%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/admin/countries/edit.html.erb
<h1>Edit Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', admin_countries_path %>

app/views/admin/countries/index.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>
  <div class="col">
    <%= link_to 'New Country', new_admin_country_path, class: 'btn btn-success' %>
  </div>
</div>
<br/>
<div class="card">
    <div class="row">
      <div class="col">
	  	<h1><%= I18n.t('admin.countries.list.header') %></h1>
      <table class="table table-striped">
        <thead>
          <tr>
            <th><%= I18n.t('admin.countries.list.country_name') %></th>
            <th><%= I18n.t('admin.countries.list.code') %></th>
            <th><%= I18n.t('admin.countries.list.active') %></th>
            <th colspan="2"></th>
          </tr>
        </thead>

        <tbody>
        <% @countries.each do |country| %>
          <tr>
            <td class="align-middle"><%= country.name %></td>
            <td class="align-middle"><%= country.code %></td>
            <td class="align-middle"><%= country.active %></td>
            <td class="align-middle"><%= link_to 'Edit', edit_admin_country_path(country) %></td>
            <td class="align-middle"><%= link_to 'Destroy', [:admin, country], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%== pagy_bootstrap_nav(@pagy) %>
      </div>
    </div>
</div> 

app/views/admin/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', admin_countries_path %>