config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'main#index'

  devise_for :users
    namespace :admin do
      root to: 'main#index'
      resources :users
      resources :vaccines_items
      resources :bookings
      resources :patients
      resources :business_units
      resources :business_unit_slots
      resources :districts
      get '/countries/fetch_cities'
      resources :countries
      get '/cities/fetch_districts'
      resources :cities
      resources :orders
      resources :sms
    end
  end

  get 'slots/fetch_cities'
  get 'slots/fetch_districts'
  get 'slots/fetch_business_units'
  resources :slots, only: [:index]

  match 'bookings/:vaccine', to: 'main#current_step', via: :get, as: :current_step
  match 'next_step', to: 'main#next_step', via: :post
  match 'prev_step', to: 'main#prev_step', via: :post

  get 'order_cancellations/find_order'
  post 'order_cancellations/send_verification'
  post 'order_cancellations/verify_code'
  resources :order_cancellations
end

app/models/business_unit_slot.rb
class BusinessUnitSlot < ApplicationRecord
  belongs_to :business_unit
  belongs_to :user

  validates :duration, :start_date, :end_date, :business_unit_id, :user_id, presence: true
  validates :duration, inclusion: { in: [5, 10, 12, 15, 20, 30] }
  scope :active, -> { where(active: true).where('end_date >= ?', Time.current) }
end

app/controllers/admin/business_unit_slots_controller.rb
module Admin
  # ...
  class BusinessUnitSlotsController < ApplicationController
    before_action :init_service

    def index
      @pagy, @slots = pagy(@slot_service.list)
    end

    def new
      result = @slot_service.new

      @slot = result.slot
    end

    def edit
      result = @slot_service.edit(params[:id])

      @slot = result.slot
    end

    def create
      result = @slot_service.create(slot_params)

      @slot = result.slot

      if result.success?
        redirect_to admin_business_unit_slots_path, notice: I18n.t('admin.slots.notices.created')
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      result = @slot_service.update(params[:id], slot_params)

      @slot = result.slot

      if result.success?
        redirect_to admin_business_unit_slots_path, notice: I18n.t('admin.slots.notices.updated')
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      result = @slot_service.delete(params[:id])

      if result.success?
        redirect_to admin_business_unit_slots_path, notice: I18n.t('admin.slots.notices.destroyed')
      end
    end

    private

    def init_service
      @slot_service = Slots::SlotService.new(current_user)
    end

    def slot_params
      params
        .require(:business_unit_slot)
        .permit(:id, :duration, :business_unit_id, :start_date, :end_date, :user_id, :active)
    end
  end
end

app/views/admin/business_unit_slots/_form.html.erb
<% if slot.errors[:base].present? %>
  <% slot.errors.each do |error| %>
    <div class="alert alert-danger" role="alert">
      <%= error.full_message %>
    </div>
  <% end %>
<% end %>

<%= simple_form_for [:admin, slot] do |f| %>
  <%= f.input :duration, as: :integer %>
  <%= f.association :business_unit %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.input :active %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/admin/business_unit_slots/edit.html.erb
<h1>New slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Back', admin_business_unit_slots_path %>>

app/views/admin/business_unit_slots/index.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>
  <div class="col">
    <%= link_to 'New Slot', new_admin_business_unit_slot_path, class: 'btn btn-success' %>
  </div>
</div>
<br/>
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col">
			<h1><%= I18n.t('admin.slots.list.header') %></h1>

			<table class="table table-striped">
				<thead>
					<tr>
						<th><%= I18n.t('admin.slots.list.business_unit_name') %></th>
						<th><%= I18n.t('admin.slots.list.duration') %></th>
						<th><%= I18n.t('admin.slots.list.start_date') %></th>
						<th><%= I18n.t('admin.slots.list.end_date') %></th>
						<th><%= I18n.t('admin.slots.list.active') %></th>
						<th><%= I18n.t('admin.slots.list.created_at') %></th>
						<th><%= I18n.t('admin.slots.list.updated_at') %></th>
						<th colspan="2"></th>
					</tr>
				</thead>

				<tbody>
					<% @slots.each do |slot| %>
					<tr>
						<td class="align-middle"><%= slot.business_unit.name %></td>
						<td class="align-middle"><%= slot.duration %></td>
						<td class="align-middle"><%= styled_date(slot.start_date)%></td>
						<td class="align-middle"><%= styled_date(slot.end_date)%></td>
						<td class="align-middle"><%= slot.active %></td>
						<td class="align-middle"><%= styled_date(slot.created_at)%></td>
						<td class="align-middle"><%= styled_date(slot.updated_at)%></td>
						<td class="align-middle"><%= link_to 'Edit', edit_admin_business_unit_slot_path(slot) %></td>
						<td class="align-middle"><%= link_to 'Destroy', [:admin, slot], method: :delete, data: { confirm: 'Are you sure?' } %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<%== pagy_bootstrap_nav(@pagy) %>
      </div>
    </div>
  </div>
</div> 

app/views/admin/business_unit_slots/new.html.erb
<h1>New slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Back', admin_business_unit_slots_path %>