config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    root to: 'main#index'

  devise_for :users
    namespace :admin do
      root to: 'main#index'
      resources :users
      resources :vaccines_items
      resources :bookings
      resources :patients
      resources :business_units
      resources :business_unit_slots
      resources :districts
      get '/countries/fetch_cities'
      resources :countries
      get '/cities/fetch_districts'
      resources :cities
      resources :orders
      resources :sms
    end
  end

  get 'slots/fetch_cities'
  get 'slots/fetch_districts'
  get 'slots/fetch_business_units'
  resources :slots, only: [:index]

  match 'bookings/:vaccine', to: 'main#current_step', via: :get, as: :current_step
  match 'next_step', to: 'main#next_step', via: :post
  match 'prev_step', to: 'main#prev_step', via: :post

  get 'order_cancellations/find_order'
  post 'order_cancellations/send_verification'
  post 'order_cancellations/verify_code'
  resources :order_cancellations
end

app/models/business_unit.rb
class BusinessUnit < ApplicationRecord
  belongs_to :country
  belongs_to :city
  belongs_to :district

  has_many :business_unit_slots

  scope :active, -> { where(active: true) }
end

app/controllers/admin/business_units_controller.rb
module Admin
  # ...
  class BusinessUnitsController < ApplicationController
    before_action :init_service
    before_action :set_default_select, only: %i[new create update edit]

    def index
      @pagy, @units = pagy(@business_units.list)
    end

    def new
      result = @business_units.new
      @unit = result.unit
    end

    def edit
      result = @business_units.edit(params[:id])

      @unit = result.unit
    end

    def create
      result = @business_units.create(unit_params)
      @unit = result.unit

      if result.success?
        redirect_to admin_business_units_path, notice: I18n.t('admin.countries.notices.created')
      else
        render :new, status: :unprocessable_entity
      end
    end

    def update
      result = @business_units.update(params[:id], unit_params)
      @unit = result.unit

      if result.success?
        redirect_to admin_business_units_path, notice: I18n.t('admin.countries.notices.updated')
      else
        render :edit, status: :unprocessable_entity
      end
    end

    def destroy
      result = @business_units.delete(params[:id])
      if result.success?
        redirect_to admin_business_units_path, notice: I18n.t('admin.countries.notices.destroyed')
      end
    end

    private

    def set_default_select
      @countries = Country.all
      @cities = []
      @districts = []
    end

    def init_service
      @business_units = Units::UnitsService.new
    end

    def unit_params
      params.require(:business_unit).permit(:id, :country_id, :city_id, :district_id, :name, :code, :active)
    end
  end
end

app/views/admin/business_units/_form.html.erb
<%= simple_form_for [:admin, unit] do |f| %>
<div class="row" data-controller="select">
  
  <%= f.label :country_id, 'Country' %>
  <%= f.collection_select :country_id, @countries.active.order(:name), :id, :name,
    { include_blank: 'Select Country' },
    class: 'form-select',
    data: { 
      action: "change->select#fetchCities",
      select_target: "country"
    } 
  %>

<%= f.label :city_id, 'City' %>
  <%= f.collection_select :city_id, @cities, :id, :name,
    { include_blank: 'Select City' },
    class: 'form-select',
    data: { 
      action: "change->select#fetchDistricts",
      select_target: "cities" } 
  %>
<%= f.label :district_id, 'District' %>
  <%= f.collection_select :district_id, @districts, :id, :name,
    { include_blank: 'Select District' },
    class: 'form-select',
    data: { 
      select_target: "districts" } 
  %>
</div>
<%= f.input :name %>
<%= f.input :code %>
<%= f.input :active %>
<%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/admin/business_units/edit.html.erb
<h1>Edit Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Back', admin_business_units_path %>

app/views/admin/business_units/index.html.erb
<div class="row">
  <p id="notice"><%= notice %></p>
  <div class="col">
    <%= link_to 'New Unit', new_admin_business_unit_path, class: 'btn btn-success' %>
  </div>
</div>
<br/>

<div class="card">
    <div class="row">
      <div class="col">
				<h1><%= I18n.t('admin.units.list.header') %></h1>
					<table class="table table-striped">
						<thead>
							<tr>
								<th><%= I18n.t('admin.units.list.country_name') %></th>
								<th><%= I18n.t('admin.units.list.city_name') %></th>
								<th><%= I18n.t('admin.units.list.district_name') %></th>
								<th><%= I18n.t('admin.units.list.name') %></th>
								<th><%= I18n.t('admin.units.list.code') %></th>
								<th><%= I18n.t('admin.units.list.active') %></th>
								<th><%= I18n.t('admin.units.list.created_at') %></th>
								<th><%= I18n.t('admin.units.list.updated_at') %></th>
								<th colspan="2"></th>
							</tr>
						</thead>

						<tbody>
						<% @units.each do |unit| %>
							<tr>
								<td class="align-middle"><%= unit.country.name %></td>
								<td class="align-middle"><%= unit.city.name %></td>
								<td class="align-middle"><%= unit.district.name %></td>
								<td class="align-middle"><%= unit.name %></td>
								<td class="align-middle"><%= unit.code %></td>
								<td class="align-middle"><%= unit.active %></td>
								<td class="align-middle"><%= styled_date(unit.created_at)%></td>
								<td class="align-middle"><%= styled_date(unit.updated_at)%></td>
								<td class="align-middle"><%= link_to 'Edit', edit_admin_business_unit_path(unit) %></td>
								<td class="align-middle"><%= link_to 'Destroy', [:admin, unit], method: :delete, data: { confirm: 'Are you sure?' } %></td>
							</tr>
						<% end %>
					</table>
					<%== pagy_bootstrap_nav(@pagy) %>
      </div>
    </div>
</div> 

app/views/admin/business_units/new.html.erb
<h1>New Unit</h1>

<%= render 'form', unit: @unit %>

<%= link_to 'Back', admin_business_units_path %>